# Generated by Django 4.2.11 on 2024-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asset_Manager_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='assetCategory',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
